# Generated by Django 5.1.2 on 2024-11-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildNameModel',
            fields=[
                ('childname_code', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='N° Clase inferior')),
            ],
        ),
        migrations.CreateModel(
            name='ClassNameModel',
            fields=[
                ('classname_code', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='N° Clase superior')),
            ],
        ),
        migrations.CreateModel(
            name='MerchStructure',
            fields=[
                ('custom_primary_key', models.SlugField(blank=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=40, verbose_name='Descripción')),
                ('hier_level', models.IntegerField(verbose_name='Nivel en jerarquía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('childname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.childnamemodel')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.classnamemodel')),
            ],
            options={
                'verbose_name': 'Estructura de Mercadería',
                'verbose_name_plural': 'Estructura de Mercaderías',
            },
        ),
    ]
